### ISSUE TITLE
Rewards Mapping from SG Prod to FAB SG - 27072023

### ISSUE THREAD

**Issue by RewardzSG** [rewardz/Ritha#2]
Hi @govind-sg Please see attached file for rewards mapping from SG Prod to FAB SG server. Total IDs to map are 52 of them, those with column "Batch Shift from SG to FAB" = YES
[Book1 (1).xlsx](https://github.com/rewardz/Ritha/files/12178940/Book1.1.xlsx)

**Comment by govind-sg** [comment]
Hi @ZhiQin,

Please find mapping ids:

```
{"9731": 228, "8427": 211, "2298": 184, "2382": 194, "8071": 209, "12728": 230, "2657": 199, "8428": 212, "8429": 213, "8425": 210, "8440": 221, "8441": 222, "9711": 227, "2806": 202, "2345": 186, "2347": 188, "2346": 187, "6873": 207, "13305": 232, "2349": 189, "3127": 203, "13083": 231, "2741": 201, "2383": 195, "2404": 198, "2030": 183, "2389": 196, "2392": 197, "8431": 215, "8430": 214, "8433": 216, "1090": 182, "8434": 217, "8437": 219, "8436": 218, "8438": 220, "9501": 225, "2702": 200, "2374": 192, "9656": 226, "9467": 224, "8004": 208, "5105": 205, "2337": 185, "5080": 204, "2378": 193, "9882": 229, "6210": 206, "2352": 191, "8549": 223, "2351": 190}
```
Apart from this, One record got skipped due to missing Terms And Conditions in the reward.
`-> "23": ["Terms And Conditions [en]"]`

Please verify it once. Thanks!
